### ISSUE TITLE
updated deps cause error

### ISSUE THREAD

**Issue by cmnstmntmn** [porsager/wright#13]
`yarn upgrade` and right after Wright throws this error.

```console
_http_outgoing.js:420
    throw new Error('Can\'t render headers after they are sent to the client');
    ^

Error: Can't render headers after they are sent to the client
    at ServerResponse._renderHeaders (_http_outgoing.js:420:11)
    at ServerResponse.writeHead (_http_server.js:187:20)
    at ServerResponse.res.end (/Users/constantin/Sites/mil-app/node_modules/wright/lib/serve.js:180:18)
    at IncomingMessage.onend (_stream_readable.js:511:10)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

as a workaround, i commented that line inside `node_modules/wright/lib/serve.js`

**Comment by porsager** [comment]
Oh don't know how I missed this one. It should be fixed by now. Sorry
